### ISSUE TITLE
iOS 报错

### ISSUE THREAD

**Issue by zhangylios** [dcloudio/native-docs#13]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Have you sent -__dcloud_io_setBackgroundColor: to <WKScrollView: 0x7f887a055800; baseClass = UIScrollView; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x600000540de0>; layer = <CALayer: 0x600000b6a5a0>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}> off the main thread? To verify, look for a complaint in the logs: "Unsupported use of UIKit…", and fix the problem if you find it. If your use is main-thread only please file a radar on UIKit, and attach this log. exercisedImplementations = {
    "__dcloud_io_setBackgroundColor:" =     (
    );

**Comment by xiaohuapunk** [comment]
感谢反馈，下个版本修复此问题

**Comment by libertyfree** [comment]
请问作者是否修复此问题,修复版本是哪个版本?

**Comment by Hsukun** [comment]
哪修复了？uniapp的3.1.2还有这个问题呢

**Comment by haohetao** [comment]
这是编译的时候还是运行的时候出一的
