### ISSUE TITLE
有交流群或者什么答疑群吗？发现最后生成APP有困难

### ISSUE THREAD

**Issue by jiazhaoyang** [dcloudio/native-docs#18]
有交流群或者什么答疑群吗？发现最后生成APP有困难，跟着项目走走着走着就走不了了，文档需要更新啊

**Comment by st-dc** [comment]
https://nativesupport.dcloud.net.cn/NativePlugin/README 文档里都有说明。 请仔细看文档 
群1：256775471  点此加入
群2：814228233  点此加入
群3：455763866  点此加入
