### ISSUE TITLE
不开源吗？

### ISSUE THREAD

**Issue by shaop** [dcloudio/native-docs#4]
这一部分 native 的代码不开源吗？

**Comment by xiaohuapunk** [comment]
源码公开策略 [https://nativesupport.dcloud.net.cn/UniMPDocs/SDKDownload/opensource?id=%e6%ba%90%e7%a0%81%e5%85%ac%e5%bc%80%e7%ad%96%e7%95%a5](https://nativesupport.dcloud.net.cn/UniMPDocs/SDKDownload/opensource?id=%e6%ba%90%e7%a0%81%e5%85%ac%e5%bc%80%e7%ad%96%e7%95%a5)
