### ISSUE TITLE
原生插件文档需要优化

### ISSUE THREAD

**Issue by runryan** [dcloudio/native-docs#7]
1、文档中需要创建一个空白项目，但是从头到尾都没有提及这个空白项目究竟是干嘛的，建议删除。如果是为了让用户在自定义了Week Module之后，在这个空白项目中使用，还希望增加一段如何集成自定义Module到自己的项目中的文档描述。
![blank_proj](https://user-images.githubusercontent.com/23459575/83834521-18cbf300-a721-11ea-81c3-e9f5c0dd2b28.png)

2、自定义Module中的方法参数是一个JSONObject，这是一个严重的误导性错误，导致在测试了好几遍，options都没有数据。根据weex文档才知道， **Module 扩展的方法可以使用 int, double, float, String, Map, List 类型的参数** 。
![module_param_error](https://user-images.githubusercontent.com/23459575/83834560-2d0ff000-a721-11ea-8638-bb29c972b11d.png)

**Comment by st-dc** [comment]
实际测试是可以JSONObject 前天是使用com.alibaba.fastjson.JSONObject; 继承自map具体可参考demo示例
